export const EXTENDED = 'EXTENDED'

export const REGISTERED_ASSETS = 'REGISTERED_ASSETS'
export const GET_COLUMNS = 'GET_COLUMNS'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const HABILITAR_EDICION_USUARIO = 'HABILITAR_EDICION_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const USUARIO_ERROR = 'USUARIO_ERROR';
export const USUARIO_ACTUAL = 'USUARIO_ACTUAL';
export const ASCENDER_USUARIO = 'ASCENDER_USUARIO';
export const DESCENDER_USUARIO = 'DESCENDER_USUARIO';
export const CAMBIAR_PASSWORD = 'CAMBIAR_PASSWORD'
export const CAMBIAR_IMAGEN_PERFIL = 'CAMBIAR_IMAGEN_PERFIL'
export const EDIT_ERROR = 'EDIT_ERROR'