export const EXTENDED = 'EXTENDED'

export const REGISTERED_ASSETS = 'REGISTERED_ASSETS'
export const GET_COLUMNS = 'GET_COLUMNS'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const RECUPERAR_PASS = 'RECUPERAR_PASS';
export const CERRAR_SESION = 'CERRAR_SESION';
export const RESET_MESSAGE = 'RESET_MESSAGE';
export const NUEVO_PASSWORD = 'NUEVO_PASSWORD';

export const ESTABLECER_ENTIDAD = 'ESTABLECER_ENTIDAD'
export const ESTABLECER_CUSTODIO = 'ESTABLECER_CUSTODIO'
export const ESTABLECER_GRUPO = 'ESTABLECER_GRUPO'


export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const HABILITAR_EDICION_USUARIO = 'HABILITAR_EDICION_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const USUARIO_ERROR = 'USUARIO_ERROR';
export const USUARIO_ACTUAL = 'USUARIO_ACTUAL';
export const ASCENDER_USUARIO = 'ASCENDER_USUARIO';
export const DESCENDER_USUARIO = 'DESCENDER_USUARIO';
export const CAMBIAR_PASSWORD = 'CAMBIAR_PASSWORD'
export const CAMBIAR_IMAGEN_PERFIL = 'CAMBIAR_IMAGEN_PERFIL'
export const EDIT_ERROR = 'EDIT_ERROR'

export const AGREGAR_PROVEEDOR = 'AGREGAR_PROVEEDOR'
export const ACTUALIZAR_PROVEEDOR = 'ACTUALIZAR_PROVEEDOR'
export const PROVEEDOR_ACTUAL = 'PROVEEDOR_ACTUAL'
export const LIMPIAR_PROVEEDOR = 'LIMPIAR_PROVEEDOR'
export const BAJA_PROVEEDOR = 'BAJA_PROVEEDOR'
export const OBTENER_PROVEEDORES = 'OBTENER_PROVEEDORES'
export const PROVEEDOR_ERROR = 'PROVEEDOR_ERROR'

export const AGREGAR_AREA = 'AGREGAR_AREA'
export const ACTUALIZAR_AREA = 'ACTUALIZAR_AREA'
export const AREA_ACTUAL = 'AREA_ACTUAL'
export const LIMPIAR_AREA = 'LIMPIAR_AREA'
export const BAJA_AREA = 'BAJA_AREA'
export const OBTENER_AREAS = 'OBTENER_AREAS'
export const AREA_ERROR = 'AREA_ERROR'

export const AGREGAR_CARGO = 'AGREGAR_CARGO'
export const ACTUALIZAR_CARGO = 'ACTUALIZAR_CARGO'
export const CARGO_ACTUAL = 'CARGO_ACTUAL'
export const LIMPIAR_CARGO = 'LIMPIAR_CARGO'
export const BAJA_CARGO = 'BAJA_CARGO'
export const OBTENER_CARGOS = 'OBTENER_CARGOS'
export const CARGO_ERROR = 'CARGO_ERROR'

export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO'
export const ACTUALIZAR_EMPLEADO = 'ACTUALIZAR_EMPLEADO'
export const EMPLEADO_ACTUAL = 'EMPLEADO_ACTUAL'
export const LIMPIAR_EMPLEADO = 'LIMPIAR_EMPLEADO'
export const BAJA_EMPLEADO = 'BAJA_EMPLEADO'
export const OBTENER_EMPLEADOS = 'OBTENER_EMPLEADOS'
export const OBTENER_TOTAL_EMPLEADOS = 'OBTENER_TOTAL_EMPLEADOS'
export const EMPLEADO_ERROR = 'EMPLEADO_ERROR'

export const AGREGAR_ACTIVO = 'AGREGAR_ACTIVO'
export const ACTUALIZAR_ACTIVO = 'ACTUALIZAR_ACTIVO'
export const ACTUALIZAR_IMAGEN_ACTIVO = 'ACTUALIZAR_IMAGEN_ACTIVO'
export const EDITAR_IMAGEN_ACTIVO = 'EDITAR_IMAGEN_ACTIVO'
export const ACTIVO_ACTUAL = 'ACTIVO_ACTUAL'
export const ACTIVO_A_DEVOLVER = 'ACTIVO_A_DEVOLVER'
export const ACTIVO_A_TRASLADAR = 'ACTIVO_A_TRASLADAR'
export const ACTIVO_BAJA = 'ACTIVO_BAJA'
export const LIMPIAR_ACTIVO = 'LIMPIAR_ACTIVO'
export const LIMPIAR_ACTIVO_A_DEVOLVER = 'LIMPIAR_ACTIVO_A_DEVOLVER'
export const LIMPIAR_ACTIVO_BAJA = 'LIMPIAR_ACTIVO_BAJA'
export const LIMPIAR_ACTIVO_A_TRASLADAR = 'LIMPIAR_ACTIVO_A_TRASLADAR'
export const BAJA_ACTIVO = 'BAJA_ACTIVO'
export const TRASLADO_ACTIVO = 'TRASLADO_ACTIVO'
export const OBTENER_ACTIVOS = 'OBTENER_ACTIVOS'
export const OBTENER_TOTAL_ACTIVOS = 'OBTENER_TOTAL_ACTIVOS'
export const OBTENER_TOTAL_ASIGNADOS = 'OBTENER_TOTAL_ASIGNADOS'
export const OBTENER_ACTIVOS_ASIGNADOS = 'OBTENER_ACTIVOS_ASIGNADOS'
export const OBTENER_ACTIVOS_NO_ASIGNADOS = 'OBTENER_ACTIVOS_NO_ASIGNADOS'
export const ASIGNAR_ACTIVO = 'ASIGNAR_ACTIVO'
export const DESVINCULAR_ACTIVO = 'DESVINCULAR_ACTIVO'
export const ACTIVO_ERROR = 'ACTIVO_ERROR'

export const ACTIVO_OBTENER_AUXILIARES = 'ACTIVO_OBTENER_AUXILIARES'
export const ACTIVO_OBTENER_GRUPOS = 'ACTIVO_OBTENER_GRUPOS'
export const ACTIVO_OBTENER_TOTAL_GRUPOS = 'ACTIVO_OBTENER_TOTAL_GRUPOS'
export const ACTIVO_OBTENER_AMBIENTES = 'ACTIVO_OBTENER_AMBIENTES'

export const REGISTRAR_DEVOLUCION = 'REGISTRAR_DEVOLUCION'
export const DEVOLUCION_ACTUAL = 'DEVOLUCION_ACTUAL'
export const LIMPIAR_DEVOLUCION = 'LIMPIAR_DEVOLUCION'
export const OBTENER_DEVOLUCIONES = 'OBTENER_DEVOLUCIONES'
export const DEVOLUCION_ERROR = 'DEVOLUCION_ERROR'

export const REGISTRAR_BAJA = 'REGISTRAR_BAJA'
export const BAJA_ACTUAL = 'BAJA_ACTUAL'
export const LIMPIAR_BAJA = 'LIMPIAR_BAJA'
export const OBTENER_BAJAS = 'OBTENER_BAJAS'
export const OBTENER_TOTAL_BAJAS = 'OBTENER_TOTAL_BAJAS'
export const BAJA_ERROR = 'BAJA_ERROR'

export const REGISTRAR_TRASLADO = 'REGISTRAR_TRASLADO'
export const TRASLADO_ACTUAL = 'TRASLADO_ACTUAL'
export const LIMPIAR_TRASLADO = 'LIMPIAR_TRASLADO'
export const OBTENER_TRASLADOS = 'OBTENER_TRASLADOS'
export const TRASLADO_ERROR = 'TRASLADO_ERROR'

export const OBTENER_POR_CUSTODIO = 'OBTENER_POR_CUSTODIO'
export const OBTENER_POR_GRUPO = 'OBTENER_POR_GRUPO'
export const OBTENER_POR_ENTIDAD = 'OBTENER_POR_ENTIDAD'
export const OBTENER_CUSTODIOS = 'OBTENER_CUSTODIOS'
export const OBTENER_GRUPOS = 'OBTENER_GRUPOS'
export const OBTENER_ENTIDADES = 'OBTENER_ENTIDADES'
export const LISTA_ERROR = 'LISTA_ERROR'
export const LIMPIAR_LISTA_CUSTODIOS = 'LIMPIAR_LISTA_CUSTODIOS'
export const LIMPIAR_LISTA_GRUPOS = 'LIMPIAR_LISTA_GRUPOS'
export const LIMPIAR_LISTA_ENTIDADES = 'LIMPIAR_LISTA_ENTIDADES'

export const OBTENER_GESTION = 'OBTENER_GESTION'
export const OBTENER_GESTIONES = 'OBTENER_GESTIONES'
export const REALIZAR_DEPRECIACION = 'REALIZAR_DEPRECIACION'
export const REGISTRAR_VALOR = 'REGISTRAR_VALOR'
export const DEPRECIACION_ERROR = 'DEPRECIACION_ERROR'
export const LIMPIAR_MENSAJE_DEPRECIACION = 'LIMPIAR_MENSAJE_DEPRECIACION'

export const AGREGAR_EDIFICIO = 'AGREGAR_EDIFICIO'
export const ACTUALIZAR_EDIFICIO = 'ACTUALIZAR_EDIFICIO'
export const EDIFICIO_ACTUAL = 'EDIFICIO_ACTUAL'
export const PISOS_EDIFICIO = 'PISOS_EDIFICIO'
export const LIMPIAR_EDIFICIO = 'LIMPIAR_EDIFICIO'
export const BAJA_EDIFICIO = 'BAJA_EDIFICIO'
export const OBTENER_EDIFICIOS = 'OBTENER_EDIFICIOS'
export const EDIFICIO_ERROR = 'EDIFICIO_ERROR'

export const AGREGAR_PISO = 'AGREGAR_PISO'
export const ACTUALIZAR_PISO = 'ACTUALIZAR_PISO'
export const PISO_ACTUAL = 'PISO_ACTUAL'
export const AMBIENTES_PISO = 'AMBIENTES_PISO'
export const LIMPIAR_PISO = 'LIMPIAR_PISO'
export const LIMPIAR_AMBIENTES_PISO = 'LIMPIAR_AMBIENTES_PISO'
export const BAJA_PISO = 'BAJA_PISO'
export const OBTENER_PISOS = 'OBTENER_PISOS'
export const FORMULARIO_PISO = 'FORMULARIO_PISO'
export const PISO_ERROR = 'PISO_ERROR'

export const AGREGAR_AMBIENTE = 'AGREGAR_AMBIENTE'
export const ACTUALIZAR_AMBIENTE = 'ACTUALIZAR_AMBIENTE'
export const AMBIENTE_ACTUAL = 'AMBIENTE_ACTUAL'
export const LIMPIAR_AMBIENTE = 'LIMPIAR_AMBIENTE'
export const BAJA_AMBIENTE = 'BAJA_AMBIENTE'
export const OBTENER_AMBIENTES = 'OBTENER_AMBIENTES'
export const FORMULARIO_AMBIENTE = 'FORMULARIO_AMBIENTE'
export const AMBIENTE_ERROR = 'AMBIENTE_ERROR'