export const EXTENDED = 'EXTENDED'

export const REGISTERED_ASSETS = 'REGISTERED_ASSETS'
export const GET_COLUMNS = 'GET_COLUMNS'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const HABILITAR_EDICION_USUARIO = 'HABILITAR_EDICION_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const USUARIO_ERROR = 'USUARIO_ERROR';
export const USUARIO_ACTUAL = 'USUARIO_ACTUAL';
export const ASCENDER_USUARIO = 'ASCENDER_USUARIO';
export const DESCENDER_USUARIO = 'DESCENDER_USUARIO';
export const CAMBIAR_PASSWORD = 'CAMBIAR_PASSWORD'
export const CAMBIAR_IMAGEN_PERFIL = 'CAMBIAR_IMAGEN_PERFIL'
export const EDIT_ERROR = 'EDIT_ERROR'

export const AGREGAR_PROVEEDOR = 'AGREGAR_PROVEEDOR'
export const ACTUALIZAR_PROVEEDOR = 'ACTUALIZAR_PROVEEDOR'
export const PROVEEDOR_ACTUAL = 'PROVEEDOR_ACTUAL'
export const LIMPIAR_PROVEEDOR = 'LIMPIAR_PROVEEDOR'
export const BAJA_PROVEEDOR = 'BAJA_PROVEEDOR'
export const OBTENER_PROVEEDORES = 'OBTENER_PROVEEDORES'
export const PROVEEDOR_ERROR = 'PROVEEDOR_ERROR'

export const AGREGAR_AREA = 'AGREGAR_AREA'
export const ACTUALIZAR_AREA = 'ACTUALIZAR_AREA'
export const AREA_ACTUAL = 'AREA_ACTUAL'
export const LIMPIAR_AREA = 'LIMPIAR_AREA'
export const BAJA_AREA = 'BAJA_AREA'
export const OBTENER_AREAS = 'OBTENER_AREAS'
export const AREA_ERROR = 'AREA_ERROR'

export const AGREGAR_CARGO = 'AGREGAR_CARGO'
export const ACTUALIZAR_CARGO = 'ACTUALIZAR_CARGO'
export const CARGO_ACTUAL = 'CARGO_ACTUAL'
export const LIMPIAR_CARGO = 'LIMPIAR_CARGO'
export const BAJA_CARGO = 'BAJA_CARGO'
export const OBTENER_CARGOS = 'OBTENER_CARGOS'
export const CARGO_ERROR = 'CARGO_ERROR'

export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO'
export const ACTUALIZAR_EMPLEADO = 'ACTUALIZAR_EMPLEADO'
export const EMPLEADO_ACTUAL = 'EMPLEADO_ACTUAL'
export const LIMPIAR_EMPLEADO = 'LIMPIAR_EMPLEADO'
export const BAJA_EMPLEADO = 'BAJA_EMPLEADO'
export const OBTENER_EMPLEADOS = 'OBTENER_EMPLEADOS'
export const EMPLEADO_ERROR = 'EMPLEADO_ERROR'

export const AGREGAR_ACTIVO = 'AGREGAR_ACTIVO'
export const ACTUALIZAR_ACTIVO = 'ACTUALIZAR_ACTIVO'
export const ACTUALIZAR_IMAGEN_ACTIVO = 'ACTUALIZAR_IMAGEN_ACTIVO'
export const EDITAR_IMAGEN_ACTIVO = 'EDITAR_IMAGEN_ACTIVO'
export const ACTIVO_ACTUAL = 'ACTIVO_ACTUAL'
export const ACTIVO_A_DEVOLVER = 'ACTIVO_A_DEVOLVER'
export const ACTIVO_BAJA = 'ACTIVO_BAJA'
export const LIMPIAR_ACTIVO = 'LIMPIAR_ACTIVO'
export const LIMPIAR_ACTIVO_A_DEVOLVER = 'LIMPIAR_ACTIVO_A_DEVOLVER'
export const LIMPIAR_ACTIVO_BAJA = 'LIMPIAR_ACTIVO_BAJA'
export const BAJA_ACTIVO = 'BAJA_ACTIVO'
export const OBTENER_ACTIVOS = 'OBTENER_ACTIVOS'
export const OBTENER_ACTIVOS_ASIGNADOS = 'OBTENER_ACTIVOS_ASIGNADOS'
export const OBTENER_ACTIVOS_NO_ASIGNADOS = 'OBTENER_ACTIVOS_NO_ASIGNADOS'
export const ASIGNAR_ACTIVO = 'ASIGNAR_ACTIVO'
export const DESVINCULAR_ACTIVO = 'DESVINCULAR_ACTIVO'
export const ACTIVO_ERROR = 'ACTIVO_ERROR'

export const ACTIVO_OBTENER_AUXILIARES = 'ACTIVO_OBTENER_AUXILIARES'
export const ACTIVO_OBTENER_GRUPOS = 'ACTIVO_OBTENER_GRUPOS'
export const ACTIVO_OBTENER_AMBIENTES = 'ACTIVO_OBTENER_AMBIENTES'

export const REGISTRAR_DEVOLUCION = 'REGISTRAR_DEVOLUCION'
export const DEVOLUCION_ACTUAL = 'DEVOLUCION_ACTUAL'
export const LIMPIAR_DEVOLUCION = 'LIMPIAR_DEVOLUCION'
export const OBTENER_DEVOLUCIONES = 'OBTENER_DEVOLUCIONES'
export const DEVOLUCION_ERROR = 'DEVOLUCION_ERROR'

export const REGISTRAR_BAJA = 'REGISTRAR_BAJA'
export const BAJA_ACTUAL = 'BAJA_ACTUAL'
export const LIMPIAR_BAJA = 'LIMPIAR_BAJA'
export const OBTENER_BAJAS = 'OBTENER_BAJAS'
export const BAJA_ERROR = 'BAJA_ERROR'